### PR TITLE
#54 Documentation using Sphinx

### PR DESCRIPTION
**Pull request by nioperas06**

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@nioperas06 Sorry. It's already merged :(

**Comment by lk-geimfari** [comment]
@nioperas06 I'll merge it, if you add sections from our wiki. Thanks!

**Comment by lk-geimfari** [comment]
Are you created project on ReadTheDocs?

**Comment by lk-geimfari** [comment]
@nioperas06 Can you, please, release the project name on ReadTheDocs? I'll add it do ReadTheDocs by myself.

**Comment by nioperas06** [comment]
Yes: [here](http://expynent.readthedocs.io/en/latest/index.html)

**Comment by lk-geimfari** [comment]
@nioperas06 Look at comment above, please.

**Comment by nioperas06** [comment]
Okay, I'll fix it!

**Comment by nioperas06** [comment]
@lk-geimfari Done!

**Comment by lk-geimfari** [comment]
@nioperas06 Thank you for understanding! I should have direct access to the resource with the documentation. So, it will be easier to keep the documentation up-to-date.

**Comment by lk-geimfari** [comment]
@nioperas06 Thank you!

**Pull request merged**
