### PR TITLE
Added Spain phone regex and IRC name regex

### PR DESCRIPTION
**Pull request by Kurolox**
The IRC one takes an IRC user that it's usually formated as (nick)!(id)@(hostname).

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@Kurolox It's has a conflict in `expynent/patterns.py`. Please, sync fork and resend you PR.

**Comment by Kurolox** [comment]
Fixed.

**Comment by lk-geimfari** [comment]
@Kurolox Thanks!

**Comment by lk-geimfari** [comment]
@Kurolox It would be great if you added tests for your regex.

**Pull request merged**
