### PR TITLE
Added regex for Nicaragua Phone numbers

### PR DESCRIPTION
**Pull request by imgglasses**
Nicaragua phone number consist of 8 digits: for example: 8888-8888.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@imgglasses Can you add test for your regex? Thank you!

**Comment by imgglasses** [comment]
In a few minutes, sure! @lk-geimfari

**Comment by lk-geimfari** [comment]
@imgglasses Thank you! Please, test 2 or more formats of phone numbers which popular in Nicaragua.

**Comment by imgglasses** [comment]
@lk-geimfari I added two more pull requests (one with a better regex and the other one with two tests) because I couldn't figure how to do it in just one request. Please feel free to fix that if you can. I'm new to github. Thanks!

**Comment by lk-geimfari** [comment]
@imgglasses It's okay. I merge it. Thank you!

**Pull request closed without merging**
