### PR TITLE
removed_compiled_email_test

### PR DESCRIPTION
**Pull request by the-zebulan**
I forgot to remove the compiled email test as well. Just noticed now.

### CODE REVIEW

**Comment by the-zebulan** [comment]
@lk-geimfari ,

I wanted to ask you how you would like me to deal with pull requests. Even though I know I can merge them by myself now, do you want me to check with you first if you approve of the changes?

**Comment by lk-geimfari** [comment]
@the-zebulan You are collaborator of this library and if you think that PR is needed (and all test passed) then just merge it. Don't ask me.

**Comment by the-zebulan** [comment]
@lk-geimfari ,

Ok, thanks. Just wanted to make sure!

**Comment by lk-geimfari** [comment]
@the-zebulan I understand. Thank you.

**Comment by the-zebulan** [comment]
@lk-geimfari ,

Oh ya, I saw your other message about adding Canadian data to Church. I'll take a look at it later today and see if I can help with that too.

**Comment by lk-geimfari** [comment]
@the-zebulan Oh yes, of course. Thank you!

**Pull request merged**
