### PR TITLE
New pattern

### PR DESCRIPTION
**Pull request by finalion**
add day and month match pattern;
add strong password pattern generate function;
improve the CN zipcode pattern, email pattern;

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@finalion Thanks!

**Comment by the-zebulan** [comment]
This PR duplicated the list of zip codes. The unsorted (previous) zip codes have been put back but now they are on top of the sorted ones...

**Comment by the-zebulan** [comment]
@lk-geimfari ,

I fixed the issues in #11

**Comment by lk-geimfari** [comment]
@the-zebulan Thanks!

**Pull request merged**
