### PR TITLE
Added license plate regex pattern from Taiwan

### PR DESCRIPTION
**Pull request by TroyCode**
Test properly on Travis CI
nice project to practice regex and learn DevOps!

### CODE REVIEW

**Comment by TroyCode** [comment]
#1

**Comment by lk-geimfari** [comment]
@the-zebulan What do you think about it?

**Comment by TroyCode** [comment]
Is license plate formatting not proper for this project?

**Comment by lk-geimfari** [comment]
@TroyCode Thank you!

**Comment by TroyCode** [comment]
@lk-geimfari  Welcome

**Pull request merged**
