### PR TITLE
Add pattern to recognize US phone number and cover with tests

### PR DESCRIPTION
**Pull request by jacksondburnette**
Hello,
Let me know if you'd like me to make any changes.

It seems like everyone has  been using a one test case per pattern strategy, so I stuck to that. However, I did load up my one test case with multiple asserts. I'd be happy to switch that up if you prefer.

Also, I kept the pattern all on one line because I thought it would be more readable(ish). But I'd be willing to change that as well if you want to adhere to pep8.

### CODE REVIEW

**Comment by the-zebulan** [comment]
I do like keeping the lines shorter to adhere to PEP8. The only other thing is using `dict.iteritems` can cause an error `AttributeError: 'dict' object has no attribute 'iteritems'` with Python 3.

**Comment by the-zebulan** [comment]
The only thing about using multiple asserts per test is that if one fails, any of them after that (inside that test) don't run.

It can get a bit long though for a single assert per test.

**Comment by jacksondburnette** [comment]
@the-zebulan, Good note on `iteritems()` raising an `AttributeError` in Python 3. I will get rid of the dictionary. Do you think I should chop it down to one test case with one assert? Or extend it out to multiple test cases?

I'll break the pattern across multiple lines.

**Comment by the-zebulan** [comment]
You could just replace `iteritems` with `items`. It may not be quite as efficient in Python 2 but it's compatible with both 2 & 3.

Personally, I like having more than one test but I know, currently, most of regexes only have one.

**Comment by jacksondburnette** [comment]
@the-zebulan, made those changes. Any thoughts?

**Comment by the-zebulan** [comment]
@jacksondburnette ,

Thanks for making those updates, looks good to me!

**Pull request merged**
